import { Region } from "@app/fractal/region";
import * as C from "@app/fractal/constants";

export const createAppContext = () => ({
  queryParamOptions: null,
  canvas: null,
  overlay: null,
  thumbnail: null,
  configurationChooser: null,
  gl: null,
  ui: null,
  fractalSets: new Map(),
  colourMaps: new Map(),
  currentMaxIterations: C.INITIAL_ITERATIONS,
  currentFractalSetId: undefined,
  currentFractalSet: undefined,
  currentJuliaConstant: undefined,
  currentColourMapId: undefined,
  currentColourMap: undefined,
  region: new Region(),
  panSpeedX: 0,
  panSpeedY: 0,
  zoomSpeed: 0,
  selectingRegion: false,
  selectingRegionInitialPt: undefined,
  selectingRegionCurrentPt: undefined,
  lastMousePt: undefined,
  bookmarkMode: false,
  bookmarks: new Map(),
  nextBookmarkId: 0,
  modalOpen: false,
  configurationSummaryOpen: false,
  smoothColouring: true,
  nextConfiguration: undefined,
  nextConfigurationCount: 0,
  pinchMemo: undefined,
});
