export {
  ALT_CLICK_ACTION,
  BARNSLEY_HOME_BOOKMARK,
  BARNSLEY_INITIAL_ITERATIONS,
  COLOUR_MODE,
  cycleFractalSetId,
  DELTA_ITERATIONS,
  DELTA_ITERATIONS_BARNSLEY,
  formatIterationSummary,
  FRACTAL_DESCRIPTORS,
  FRACTAL_KIND,
  FRACTAL_SET_ID_BARNSLEY,
  FRACTAL_SET_ID_JULIA,
  FRACTAL_SET_ID_MANDELBROT,
  FRACTAL_SET_IDS,
  getFractal,
  getFractalIds,
  getHomeBookmark,
  getIterationControlLabel,
  getIterationDelta,
  getMaxIterations,
  getMinIterations,
  HOME_BOOKMARK,
  INITIAL_ITERATIONS,
  isEscapeTimeFractal,
  JULIA_HOME_BOOKMARK,
  MAX_ITERATIONS_BARNSLEY,
  MAX_ITERATIONS_MANUAL,
  MIN_ITERATIONS,
  shouldFlipPanY,
  showJuliaConstantInSummary,
  supportsInterestScoring,
  supportsJuliaConstant,
  supportsSmoothColouring,
} from "./fractal-descriptors";

import {
  FRACTAL_SET_ID_MANDELBROT,
  INITIAL_ITERATIONS,
} from "./fractal-descriptors";

export const COLOUR_MAP_NAMES = [
  "jet",
  "hsv",
  "hot",
  "cool",
  "warm",
  "spring",
  "summer",
  "autumn",
  "winter",
  "bone",
  "copper",
  "greys",
  "YIOrRd",
  "bluered",
  "RdBu",
  "picnic",
  "rainbow",
  "portland",
  "blackbody",
  "earth",
  "electric",
  "viridis",
  "inferno",
  "magma",
  "plasma",
  "rainbow-soft",
  "bathymetry",
  "cdom",
  "chlorophyll",
  "density",
  "freesurface-blue",
  "freesurface-red",
];

export const INITIAL_BOOKMARK = {
  fractalSetId: FRACTAL_SET_ID_MANDELBROT,
  juliaConstant: { x: 0, y: 0 },
  colourMapId: 0,
  regionBottomLeft: { x: -0.22, y: -0.7 },
  regionTopRight: { x: -0.21, y: -0.69 },
  maxIterations: INITIAL_ITERATIONS,
};
